@startuml
!pragma layout smetana
(*)  --> "Land on Plot"


  --> [Yes] If "Is owner currentPlayer?  " then
     --> [Yes]  If "Field is monopolized?  "
        --> [Yes] If "Give option to build   "

      Endif

      Endif

      Endif





@enduml