@startuml
'https://plantuml.com/sequence-diagram



Game -> Game: buildBoard()
'indsæt kald til readBoardData i FIleIO
'indsæt kald til konstruktoren i Board
'indsæt kald til createFields
'indsæt loop
'indsæt kald til konstruktoren i Field
'indsæt kald til readBoardData
'indsæt kald til konstruktoren i CardDeck
'indsæt kald til createCards
'indsæt kald til konstruktoren i Card
@enduml

